# Generated by Django 5.1.12 on 2025-10-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="abono",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado_pago",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estados_pagos",
                to="pedidos.estadopago",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado_pedido",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estados_pedidos",
                to="pedidos.estadopedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="subtotal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
