# Generated by Django 5.1.12 on 2025-10-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="estado_producto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estados_productos",
                to="productos.estadoproducto",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_unitario",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
