# Generated by Django 5.2.5 on 2025-10-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_alter_producto_descripcion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
    ]
