# Generated by Django 5.2.5 on 2025-10-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_categoriamedida"),
    ]

    operations = [
        migrations.AddField(
            model_name="medida",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="productos.categoriamedida",
            ),
        ),
    ]
